ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
tasks:
- before: sdk use java 11.0.2-open
  init: >
    mvn install
  command: >
    gp open src/main/java/com/applitools/quickstarts/BasicDemo.java &&
    mvn exec:java