image: selenium/standalone-chrome-debug
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
tasks:
- init: >
    mvn install
  command: >
    cd phoenicis-javafx/ &&
    mvn exec:java